CREATE TABLE `yard` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR (200) NOT NULL,
  `description` TEXT,
  `contract_total_amount` DECIMAL(12, 2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `income` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `yard_id` INT(11) NOT NULL,
  `invoice_id` INT(11) NOT NULL,
  `amount` DECIMAL(12, 2) NOT NULL,
  `status` TINYINT NOT NULL,
  `note` TEXT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`yard_id`) REFERENCES `yard` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;

CREATE TABLE `expense` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `yard_id` INT(11) NOT NULL,
  `invoice_id` INT(11) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `amount` DECIMAL(12, 2) NOT NULL,
  `status` TINYINT NOT NULL,
  `category` TINYINT NOT NULL,
  `note` TEXT,
  `emission_at` DATETIME NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`yard_id`) REFERENCES `yard` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;